/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class AndreasenHugeVolatilityAdapter extends BlackVolTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AndreasenHugeVolatilityAdapter(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.AndreasenHugeVolatilityAdapter_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndreasenHugeVolatilityAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_AndreasenHugeVolatilityAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AndreasenHugeVolatilityAdapter(AndreasenHugeVolatilityInterpl volInterpl, double eps) {
    this(QuantLibJNI.new_AndreasenHugeVolatilityAdapter__SWIG_0(AndreasenHugeVolatilityInterpl.getCPtr(volInterpl), volInterpl, eps), true);
  }

  public AndreasenHugeVolatilityAdapter(AndreasenHugeVolatilityInterpl volInterpl) {
    this(QuantLibJNI.new_AndreasenHugeVolatilityAdapter__SWIG_1(AndreasenHugeVolatilityInterpl.getCPtr(volInterpl), volInterpl), true);
  }

}
