/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class AUCPI extends ZeroInflationIndex {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AUCPI(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.AUCPI_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AUCPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_AUCPI(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AUCPI(Frequency frequency, boolean revised, boolean interpolated, ZeroInflationTermStructureHandle h) {
    this(QuantLibJNI.new_AUCPI__SWIG_0(frequency.swigValue(), revised, interpolated, ZeroInflationTermStructureHandle.getCPtr(h), h), true);
  }

  public AUCPI(Frequency frequency, boolean revised, boolean interpolated) {
    this(QuantLibJNI.new_AUCPI__SWIG_1(frequency.swigValue(), revised, interpolated), true);
  }

}
