/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class BachelierSwaptionEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BachelierSwaptionEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BachelierSwaptionEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BachelierSwaptionEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_BachelierSwaptionEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BachelierSwaptionEngine(YieldTermStructureHandle discountCurve, QuoteHandle vol, DayCounter dc) {
    this(QuantLibJNI.new_BachelierSwaptionEngine__SWIG_0(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, QuoteHandle.getCPtr(vol), vol, DayCounter.getCPtr(dc), dc), true);
  }

  public BachelierSwaptionEngine(YieldTermStructureHandle discountCurve, QuoteHandle vol) {
    this(QuantLibJNI.new_BachelierSwaptionEngine__SWIG_1(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, QuoteHandle.getCPtr(vol), vol), true);
  }

  public BachelierSwaptionEngine(YieldTermStructureHandle discountCurve, SwaptionVolatilityStructureHandle v) {
    this(QuantLibJNI.new_BachelierSwaptionEngine__SWIG_2(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, SwaptionVolatilityStructureHandle.getCPtr(v), v), true);
  }

}
