/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class BermudanExercise extends Exercise {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BermudanExercise(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BermudanExercise_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BermudanExercise obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_BermudanExercise(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BermudanExercise(DateVector dates, boolean payoffAtExpiry) {
    this(QuantLibJNI.new_BermudanExercise__SWIG_0(DateVector.getCPtr(dates), dates, payoffAtExpiry), true);
  }

  public BermudanExercise(DateVector dates) {
    this(QuantLibJNI.new_BermudanExercise__SWIG_1(DateVector.getCPtr(dates), dates), true);
  }

}
