/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class BondHelper extends RateHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected BondHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BondHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BondHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_BondHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BondHelper(QuoteHandle cleanPrice, Bond bond, BondPrice.Type priceType) {
    this(QuantLibJNI.new_BondHelper__SWIG_0(QuoteHandle.getCPtr(cleanPrice), cleanPrice, Bond.getCPtr(bond), bond, priceType.swigValue()), true);
  }

  public BondHelper(QuoteHandle cleanPrice, Bond bond) {
    this(QuantLibJNI.new_BondHelper__SWIG_1(QuoteHandle.getCPtr(cleanPrice), cleanPrice, Bond.getCPtr(bond), bond), true);
  }

  public Bond bond() {
    long cPtr = QuantLibJNI.BondHelper_bond(swigCPtr, this);
    return (cPtr == 0) ? null : new Bond(cPtr, true);
  }

}
