/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class CalibrationPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CalibrationPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrationPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CalibrationPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CalibrationPair() {
    this(QuantLibJNI.new_CalibrationPair__SWIG_0(), true);
  }

  public CalibrationPair(VanillaOption first, Quote second) {
    this(QuantLibJNI.new_CalibrationPair__SWIG_1(VanillaOption.getCPtr(first), first, Quote.getCPtr(second), second), true);
  }

  public CalibrationPair(CalibrationPair other) {
    this(QuantLibJNI.new_CalibrationPair__SWIG_2(CalibrationPair.getCPtr(other), other), true);
  }

  public void setFirst(VanillaOption value) {
    QuantLibJNI.CalibrationPair_first_set(swigCPtr, this, VanillaOption.getCPtr(value), value);
  }

  public VanillaOption getFirst() {
    long cPtr = QuantLibJNI.CalibrationPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VanillaOption(cPtr, true);
  }

  public void setSecond(Quote value) {
    QuantLibJNI.CalibrationPair_second_set(swigCPtr, this, Quote.getCPtr(value), value);
  }

  public Quote getSecond() {
    long cPtr = QuantLibJNI.CalibrationPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Quote(cPtr, true);
  }

}
