/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class Claim {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Claim(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Claim obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Claim(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double amount(Date defaultDate, double notional, double recoveryRate) {
    return QuantLibJNI.Claim_amount(swigCPtr, this, Date.getCPtr(defaultDate), defaultDate, notional, recoveryRate);
  }

}
