/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class ConvexMonotoneInterpolation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConvexMonotoneInterpolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConvexMonotoneInterpolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ConvexMonotoneInterpolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConvexMonotoneInterpolation(Array x, Array y, double quadraticity, double monotonicity, boolean forcePositive) {
    this(QuantLibJNI.new_ConvexMonotoneInterpolation__SWIG_0(Array.getCPtr(x), x, Array.getCPtr(y), y, quadraticity, monotonicity, forcePositive), true);
  }

  public ConvexMonotoneInterpolation(Array x, Array y, double quadraticity, double monotonicity) {
    this(QuantLibJNI.new_ConvexMonotoneInterpolation__SWIG_1(Array.getCPtr(x), x, Array.getCPtr(y), y, quadraticity, monotonicity), true);
  }

  public ConvexMonotoneInterpolation(Array x, Array y, double quadraticity) {
    this(QuantLibJNI.new_ConvexMonotoneInterpolation__SWIG_2(Array.getCPtr(x), x, Array.getCPtr(y), y, quadraticity), true);
  }

  public ConvexMonotoneInterpolation(Array x, Array y) {
    this(QuantLibJNI.new_ConvexMonotoneInterpolation__SWIG_3(Array.getCPtr(x), x, Array.getCPtr(y), y), true);
  }

  public double getValue(double x, boolean allowExtrapolation) {
    return QuantLibJNI.ConvexMonotoneInterpolation_getValue__SWIG_0(swigCPtr, this, x, allowExtrapolation);
  }

  public double getValue(double x) {
    return QuantLibJNI.ConvexMonotoneInterpolation_getValue__SWIG_1(swigCPtr, this, x);
  }

}
