/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class DirichletBC extends DefaultBoundaryCondition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected DirichletBC(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.DirichletBC_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirichletBC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_DirichletBC(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DirichletBC(double value, DefaultBoundaryCondition.Side side) {
    this(QuantLibJNI.new_DirichletBC(value, side.swigValue()), true);
  }

}
