/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class ExtOUWithJumpsProcess extends StochasticProcess {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ExtOUWithJumpsProcess(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ExtOUWithJumpsProcess_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtOUWithJumpsProcess obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ExtOUWithJumpsProcess(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExtOUWithJumpsProcess(ExtendedOrnsteinUhlenbeckProcess process, double Y0, double beta, double jumpIntensity, double eta) {
    this(QuantLibJNI.new_ExtOUWithJumpsProcess(ExtendedOrnsteinUhlenbeckProcess.getCPtr(process), process, Y0, beta, jumpIntensity, eta), true);
  }

}
