/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmArithmeticAverageCondition extends FdmStepCondition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmArithmeticAverageCondition(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmArithmeticAverageCondition_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmArithmeticAverageCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmArithmeticAverageCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmArithmeticAverageCondition(DoubleVector averageTimes, double arg1, long pastFixings, FdmMesher mesher, long equityDirection) {
    this(QuantLibJNI.new_FdmArithmeticAverageCondition(DoubleVector.getCPtr(averageTimes), averageTimes, arg1, pastFixings, FdmMesher.getCPtr(mesher), mesher, equityDirection), true);
  }

}
