/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmBlackScholesOp extends FdmLinearOpComposite {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmBlackScholesOp(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmBlackScholesOp_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmBlackScholesOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmBlackScholesOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmBlackScholesOp(FdmMesher mesher, GeneralizedBlackScholesProcess process, double strike, boolean localVol, double illegalLocalVolOverwrite, long direction, FdmQuantoHelper quantoHelper) {
    this(QuantLibJNI.new_FdmBlackScholesOp__SWIG_0(FdmMesher.getCPtr(mesher), mesher, GeneralizedBlackScholesProcess.getCPtr(process), process, strike, localVol, illegalLocalVolOverwrite, direction, FdmQuantoHelper.getCPtr(quantoHelper), quantoHelper), true);
  }

  public FdmBlackScholesOp(FdmMesher mesher, GeneralizedBlackScholesProcess process, double strike, boolean localVol, double illegalLocalVolOverwrite, long direction) {
    this(QuantLibJNI.new_FdmBlackScholesOp__SWIG_1(FdmMesher.getCPtr(mesher), mesher, GeneralizedBlackScholesProcess.getCPtr(process), process, strike, localVol, illegalLocalVolOverwrite, direction), true);
  }

  public FdmBlackScholesOp(FdmMesher mesher, GeneralizedBlackScholesProcess process, double strike, boolean localVol, double illegalLocalVolOverwrite) {
    this(QuantLibJNI.new_FdmBlackScholesOp__SWIG_2(FdmMesher.getCPtr(mesher), mesher, GeneralizedBlackScholesProcess.getCPtr(process), process, strike, localVol, illegalLocalVolOverwrite), true);
  }

  public FdmBlackScholesOp(FdmMesher mesher, GeneralizedBlackScholesProcess process, double strike, boolean localVol) {
    this(QuantLibJNI.new_FdmBlackScholesOp__SWIG_3(FdmMesher.getCPtr(mesher), mesher, GeneralizedBlackScholesProcess.getCPtr(process), process, strike, localVol), true);
  }

  public FdmBlackScholesOp(FdmMesher mesher, GeneralizedBlackScholesProcess process, double strike) {
    this(QuantLibJNI.new_FdmBlackScholesOp__SWIG_4(FdmMesher.getCPtr(mesher), mesher, GeneralizedBlackScholesProcess.getCPtr(process), process, strike), true);
  }

}
