/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmCEV1dMesher extends Fdm1dMesher {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmCEV1dMesher(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmCEV1dMesher_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmCEV1dMesher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmCEV1dMesher(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmCEV1dMesher(long size, double f0, double alpha, double beta, double maturity, double eps, double scaleFactor, DoublePair cPoint) {
    this(QuantLibJNI.new_FdmCEV1dMesher__SWIG_0(size, f0, alpha, beta, maturity, eps, scaleFactor, DoublePair.getCPtr(cPoint), cPoint), true);
  }

  public FdmCEV1dMesher(long size, double f0, double alpha, double beta, double maturity, double eps, double scaleFactor) {
    this(QuantLibJNI.new_FdmCEV1dMesher__SWIG_1(size, f0, alpha, beta, maturity, eps, scaleFactor), true);
  }

  public FdmCEV1dMesher(long size, double f0, double alpha, double beta, double maturity, double eps) {
    this(QuantLibJNI.new_FdmCEV1dMesher__SWIG_2(size, f0, alpha, beta, maturity, eps), true);
  }

  public FdmCEV1dMesher(long size, double f0, double alpha, double beta, double maturity) {
    this(QuantLibJNI.new_FdmCEV1dMesher__SWIG_3(size, f0, alpha, beta, maturity), true);
  }

}
