/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmDividendHandler extends FdmStepCondition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmDividendHandler(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmDividendHandler_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmDividendHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmDividendHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmDividendHandler(DividendSchedule schedule, FdmMesher mesher, Date referenceDate, DayCounter dayCounter, long equityDirection) {
    this(QuantLibJNI.new_FdmDividendHandler(DividendSchedule.getCPtr(schedule), schedule, FdmMesher.getCPtr(mesher), mesher, Date.getCPtr(referenceDate), referenceDate, DayCounter.getCPtr(dayCounter), dayCounter, equityDirection), true);
  }

  public DoubleVector dividendTimes() {
    return new DoubleVector(QuantLibJNI.FdmDividendHandler_dividendTimes(swigCPtr, this), false);
  }

  public DateVector dividendDates() {
    return new DateVector(QuantLibJNI.FdmDividendHandler_dividendDates(swigCPtr, this), false);
  }

  public DoubleVector dividends() {
    return new DoubleVector(QuantLibJNI.FdmDividendHandler_dividends(swigCPtr, this), false);
  }

}
