/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmHestonOp extends FdmLinearOpComposite {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmHestonOp(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmHestonOp_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmHestonOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmHestonOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmHestonOp(FdmMesher mesher, HestonProcess hestonProcess, FdmQuantoHelper quantoHelper, LocalVolTermStructure leverageFct) {
    this(QuantLibJNI.new_FdmHestonOp__SWIG_0(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(hestonProcess), hestonProcess, FdmQuantoHelper.getCPtr(quantoHelper), quantoHelper, LocalVolTermStructure.getCPtr(leverageFct), leverageFct), true);
  }

  public FdmHestonOp(FdmMesher mesher, HestonProcess hestonProcess, FdmQuantoHelper quantoHelper) {
    this(QuantLibJNI.new_FdmHestonOp__SWIG_1(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(hestonProcess), hestonProcess, FdmQuantoHelper.getCPtr(quantoHelper), quantoHelper), true);
  }

  public FdmHestonOp(FdmMesher mesher, HestonProcess hestonProcess) {
    this(QuantLibJNI.new_FdmHestonOp__SWIG_2(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(hestonProcess), hestonProcess), true);
  }

}
