/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmHullWhiteSolver {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FdmHullWhiteSolver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmHullWhiteSolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_FdmHullWhiteSolver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FdmHullWhiteSolver(HullWhite model, FdmSolverDesc solverDesc, FdmSchemeDesc schemeDesc) {
    this(QuantLibJNI.new_FdmHullWhiteSolver__SWIG_0(HullWhite.getCPtr(model), model, FdmSolverDesc.getCPtr(solverDesc), solverDesc, FdmSchemeDesc.getCPtr(schemeDesc), schemeDesc), true);
  }

  public FdmHullWhiteSolver(HullWhite model, FdmSolverDesc solverDesc) {
    this(QuantLibJNI.new_FdmHullWhiteSolver__SWIG_1(HullWhite.getCPtr(model), model, FdmSolverDesc.getCPtr(solverDesc), solverDesc), true);
  }

  public double valueAt(double r) {
    return QuantLibJNI.FdmHullWhiteSolver_valueAt(swigCPtr, this, r);
  }

}
