/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmHestonGreensFct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FdmHestonGreensFct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmHestonGreensFct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_FdmHestonGreensFct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public final static class Algorithm {
    public final static FdmHestonGreensFct.Algorithm ZeroCorrelation = new FdmHestonGreensFct.Algorithm("ZeroCorrelation");
    public final static FdmHestonGreensFct.Algorithm Gaussian = new FdmHestonGreensFct.Algorithm("Gaussian");
    public final static FdmHestonGreensFct.Algorithm SemiAnalytical = new FdmHestonGreensFct.Algorithm("SemiAnalytical");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Algorithm swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Algorithm.class + " with value " + swigValue);
    }

    private Algorithm(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Algorithm(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Algorithm(String swigName, Algorithm swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Algorithm[] swigValues = { ZeroCorrelation, Gaussian, SemiAnalytical };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
