/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmHestonFwdOp extends FdmLinearOpComposite {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmHestonFwdOp(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmHestonFwdOp_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmHestonFwdOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmHestonFwdOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmHestonFwdOp(FdmMesher mesher, HestonProcess process, FdmSquareRootFwdOp.TransformationType type, LocalVolTermStructure leverageFct) {
    this(QuantLibJNI.new_FdmHestonFwdOp__SWIG_0(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(process), process, type.swigValue(), LocalVolTermStructure.getCPtr(leverageFct), leverageFct), true);
  }

  public FdmHestonFwdOp(FdmMesher mesher, HestonProcess process, FdmSquareRootFwdOp.TransformationType type) {
    this(QuantLibJNI.new_FdmHestonFwdOp__SWIG_1(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(process), process, type.swigValue()), true);
  }

  public FdmHestonFwdOp(FdmMesher mesher, HestonProcess process) {
    this(QuantLibJNI.new_FdmHestonFwdOp__SWIG_2(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(process), process), true);
  }

}
