/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmIndicesOnBoundary {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FdmIndicesOnBoundary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmIndicesOnBoundary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_FdmIndicesOnBoundary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FdmIndicesOnBoundary(FdmLinearOpLayout l, long direction, FdmBoundaryCondition.Side side) {
    this(QuantLibJNI.new_FdmIndicesOnBoundary(FdmLinearOpLayout.getCPtr(l), l, direction, side.swigValue()), true);
  }

  public UnsignedIntVector getIndices() {
    return new UnsignedIntVector(QuantLibJNI.FdmIndicesOnBoundary_getIndices(swigCPtr, this), true);
  }

}
