/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmQuantoHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FdmQuantoHelper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmQuantoHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_FdmQuantoHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FdmQuantoHelper(YieldTermStructure rTS, YieldTermStructure fTS, BlackVolTermStructure fxVolTS, double equityFxCorrelation, double exchRateATMlevel) {
    this(QuantLibJNI.new_FdmQuantoHelper(YieldTermStructure.getCPtr(rTS), rTS, YieldTermStructure.getCPtr(fTS), fTS, BlackVolTermStructure.getCPtr(fxVolTS), fxVolTS, equityFxCorrelation, exchRateATMlevel), true);
  }

}
