/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmSnapshotCondition extends FdmStepCondition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmSnapshotCondition(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmSnapshotCondition_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmSnapshotCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmSnapshotCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmSnapshotCondition(double t) {
    this(QuantLibJNI.new_FdmSnapshotCondition(t), true);
  }

  public double getTime() {
    return QuantLibJNI.FdmSnapshotCondition_getTime(swigCPtr, this);
  }

  public Array getValues() {
    return new Array(QuantLibJNI.FdmSnapshotCondition_getValues(swigCPtr, this), false);
  }

}
