/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmSabrOp extends FdmLinearOpComposite {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmSabrOp(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmSabrOp_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmSabrOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmSabrOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmSabrOp(FdmMesher mesher, YieldTermStructure rTS, double f0, double alpha, double beta, double nu, double rho) {
    this(QuantLibJNI.new_FdmSabrOp(FdmMesher.getCPtr(mesher), mesher, YieldTermStructure.getCPtr(rTS), rTS, f0, alpha, beta, nu, rho), true);
  }

}
