/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FdmSimpleSwingCondition extends FdmStepCondition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmSimpleSwingCondition(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmSimpleSwingCondition_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmSimpleSwingCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmSimpleSwingCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FdmSimpleSwingCondition(DoubleVector exerciseTimes, FdmMesher mesher, FdmInnerValueCalculator calculator, long swingDirection, long minExercises) {
    this(QuantLibJNI.new_FdmSimpleSwingCondition__SWIG_0(DoubleVector.getCPtr(exerciseTimes), exerciseTimes, FdmMesher.getCPtr(mesher), mesher, FdmInnerValueCalculator.getCPtr(calculator), calculator, swingDirection, minExercises), true);
  }

  public FdmSimpleSwingCondition(DoubleVector exerciseTimes, FdmMesher mesher, FdmInnerValueCalculator calculator, long swingDirection) {
    this(QuantLibJNI.new_FdmSimpleSwingCondition__SWIG_1(DoubleVector.getCPtr(exerciseTimes), exerciseTimes, FdmMesher.getCPtr(mesher), mesher, FdmInnerValueCalculator.getCPtr(calculator), calculator, swingDirection), true);
  }

}
