/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FixedRateCoupon extends Coupon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FixedRateCoupon(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FixedRateCoupon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FixedRateCoupon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FixedRateCoupon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FixedRateCoupon(Date paymentDate, double nominal, double rate, DayCounter dayCounter, Date startDate, Date endDate, Date refPeriodStart, Date refPeriodEnd, Date exCouponDate) {
    this(QuantLibJNI.new_FixedRateCoupon__SWIG_0(Date.getCPtr(paymentDate), paymentDate, nominal, rate, DayCounter.getCPtr(dayCounter), dayCounter, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd, Date.getCPtr(exCouponDate), exCouponDate), true);
  }

  public FixedRateCoupon(Date paymentDate, double nominal, double rate, DayCounter dayCounter, Date startDate, Date endDate, Date refPeriodStart, Date refPeriodEnd) {
    this(QuantLibJNI.new_FixedRateCoupon__SWIG_1(Date.getCPtr(paymentDate), paymentDate, nominal, rate, DayCounter.getCPtr(dayCounter), dayCounter, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Date.getCPtr(refPeriodStart), refPeriodStart, Date.getCPtr(refPeriodEnd), refPeriodEnd), true);
  }

  public FixedRateCoupon(Date paymentDate, double nominal, double rate, DayCounter dayCounter, Date startDate, Date endDate, Date refPeriodStart) {
    this(QuantLibJNI.new_FixedRateCoupon__SWIG_2(Date.getCPtr(paymentDate), paymentDate, nominal, rate, DayCounter.getCPtr(dayCounter), dayCounter, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate, Date.getCPtr(refPeriodStart), refPeriodStart), true);
  }

  public FixedRateCoupon(Date paymentDate, double nominal, double rate, DayCounter dayCounter, Date startDate, Date endDate) {
    this(QuantLibJNI.new_FixedRateCoupon__SWIG_3(Date.getCPtr(paymentDate), paymentDate, nominal, rate, DayCounter.getCPtr(dayCounter), dayCounter, Date.getCPtr(startDate), startDate, Date.getCPtr(endDate), endDate), true);
  }

  public InterestRate interestRate() {
    return new InterestRate(QuantLibJNI.FixedRateCoupon_interestRate(swigCPtr, this), true);
  }

}
