/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class FlatHazardRate extends DefaultProbabilityTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FlatHazardRate(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FlatHazardRate_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlatHazardRate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FlatHazardRate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FlatHazardRate(int settlementDays, Calendar calendar, QuoteHandle hazardRate, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatHazardRate__SWIG_0(settlementDays, Calendar.getCPtr(calendar), calendar, QuoteHandle.getCPtr(hazardRate), hazardRate, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public FlatHazardRate(Date todaysDate, QuoteHandle hazardRate, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatHazardRate__SWIG_1(Date.getCPtr(todaysDate), todaysDate, QuoteHandle.getCPtr(hazardRate), hazardRate, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

}
