/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class GlobalBootstrap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GlobalBootstrap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalBootstrap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GlobalBootstrap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GlobalBootstrap(double accuracy) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_0(accuracy), true);
  }

  public GlobalBootstrap() {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_1(), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates, double accuracy) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_2(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates, accuracy), true);
  }

  public GlobalBootstrap(RateHelperVector additionalHelpers, DateVector additionalDates) {
    this(QuantLibJNI.new_GlobalBootstrap__SWIG_3(RateHelperVector.getCPtr(additionalHelpers), additionalHelpers, DateVector.getCPtr(additionalDates), additionalDates), true);
  }

}
