/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class Glued1dMesher extends Fdm1dMesher {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Glued1dMesher(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.Glued1dMesher_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Glued1dMesher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_Glued1dMesher(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Glued1dMesher(Fdm1dMesher leftMesher, Fdm1dMesher rightMesher) {
    this(QuantLibJNI.new_Glued1dMesher(Fdm1dMesher.getCPtr(leftMesher), leftMesher, Fdm1dMesher.getCPtr(rightMesher), rightMesher), true);
  }

}
