/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class InflationIndex extends Index {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected InflationIndex(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.InflationIndex_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InflationIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_InflationIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String familyName() {
    return QuantLibJNI.InflationIndex_familyName(swigCPtr, this);
  }

  public Region region() {
    return new Region(QuantLibJNI.InflationIndex_region(swigCPtr, this), true);
  }

  public boolean revised() {
    return QuantLibJNI.InflationIndex_revised(swigCPtr, this);
  }

  public boolean interpolated() {
    return QuantLibJNI.InflationIndex_interpolated(swigCPtr, this);
  }

  public Frequency frequency() {
    return Frequency.swigToEnum(QuantLibJNI.InflationIndex_frequency(swigCPtr, this));
  }

  public Period availabilityLag() {
    return new Period(QuantLibJNI.InflationIndex_availabilityLag(swigCPtr, this), true);
  }

  public Currency currency() {
    return new Currency(QuantLibJNI.InflationIndex_currency(swigCPtr, this), true);
  }

}
