/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class JamshidianSwaptionEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected JamshidianSwaptionEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.JamshidianSwaptionEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JamshidianSwaptionEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_JamshidianSwaptionEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public JamshidianSwaptionEngine(OneFactorAffineModel model, YieldTermStructureHandle termStructure) {
    this(QuantLibJNI.new_JamshidianSwaptionEngine__SWIG_0(OneFactorAffineModel.getCPtr(model), model, YieldTermStructureHandle.getCPtr(termStructure), termStructure), true);
  }

  public JamshidianSwaptionEngine(OneFactorAffineModel model) {
    this(QuantLibJNI.new_JamshidianSwaptionEngine__SWIG_1(OneFactorAffineModel.getCPtr(model), model), true);
  }

}
