/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class LocalVolTermStructure extends VolatilityTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected LocalVolTermStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.LocalVolTermStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalVolTermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_LocalVolTermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double localVol(Date arg0, double u, boolean extrapolate) {
    return QuantLibJNI.LocalVolTermStructure_localVol__SWIG_0(swigCPtr, this, Date.getCPtr(arg0), arg0, u, extrapolate);
  }

  public double localVol(Date arg0, double u) {
    return QuantLibJNI.LocalVolTermStructure_localVol__SWIG_1(swigCPtr, this, Date.getCPtr(arg0), arg0, u);
  }

  public double localVol(double arg0, double u, boolean extrapolate) {
    return QuantLibJNI.LocalVolTermStructure_localVol__SWIG_2(swigCPtr, this, arg0, u, extrapolate);
  }

  public double localVol(double arg0, double u) {
    return QuantLibJNI.LocalVolTermStructure_localVol__SWIG_3(swigCPtr, this, arg0, u);
  }

}
