/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class MCLDForwardEuropeanHestonEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MCLDForwardEuropeanHestonEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MCLDForwardEuropeanHestonEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MCLDForwardEuropeanHestonEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_MCLDForwardEuropeanHestonEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate, int requiredSamples, double requiredTolerance, int maxSamples, int seed, boolean controlVariate) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_0(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate, requiredSamples, requiredTolerance, maxSamples, seed, controlVariate), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate, int requiredSamples, double requiredTolerance, int maxSamples, int seed) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_1(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate, requiredSamples, requiredTolerance, maxSamples, seed), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate, int requiredSamples, double requiredTolerance, int maxSamples) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_2(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate, requiredSamples, requiredTolerance, maxSamples), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate, int requiredSamples, double requiredTolerance) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_3(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate, requiredSamples, requiredTolerance), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate, int requiredSamples) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_4(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate, requiredSamples), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear, boolean antitheticVariate) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_5(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear, antitheticVariate), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps, int timeStepsPerYear) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_6(HestonProcess.getCPtr(process), process, timeSteps, timeStepsPerYear), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process, int timeSteps) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_7(HestonProcess.getCPtr(process), process, timeSteps), true);
  }

  public MCLDForwardEuropeanHestonEngine(HestonProcess process) {
    this(QuantLibJNI.new_MCLDForwardEuropeanHestonEngine__SWIG_8(HestonProcess.getCPtr(process), process), true);
  }

}
