/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class MoroInvCumulativeLecuyerGaussianRsg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MoroInvCumulativeLecuyerGaussianRsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MoroInvCumulativeLecuyerGaussianRsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MoroInvCumulativeLecuyerGaussianRsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MoroInvCumulativeLecuyerGaussianRsg(LecuyerUniformRsg uniformSequenceGenerator) {
    this(QuantLibJNI.new_MoroInvCumulativeLecuyerGaussianRsg__SWIG_0(LecuyerUniformRsg.getCPtr(uniformSequenceGenerator), uniformSequenceGenerator), true);
  }

  public MoroInvCumulativeLecuyerGaussianRsg(LecuyerUniformRsg uniformSequenceGenerator, MoroInverseCumulativeNormal inverseCumulative) {
    this(QuantLibJNI.new_MoroInvCumulativeLecuyerGaussianRsg__SWIG_1(LecuyerUniformRsg.getCPtr(uniformSequenceGenerator), uniformSequenceGenerator, MoroInverseCumulativeNormal.getCPtr(inverseCumulative), inverseCumulative), true);
  }

  public SampleRealVector nextSequence() {
    return new SampleRealVector(QuantLibJNI.MoroInvCumulativeLecuyerGaussianRsg_nextSequence(swigCPtr, this), false);
  }

  public long dimension() {
    return QuantLibJNI.MoroInvCumulativeLecuyerGaussianRsg_dimension(swigCPtr, this);
  }

}
