/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class OneFactorAffineModel extends ShortRateModel {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected OneFactorAffineModel(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.OneFactorAffineModel_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OneFactorAffineModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_OneFactorAffineModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double discountBond(double now, double maturity, Array factors) {
    return QuantLibJNI.OneFactorAffineModel_discountBond__SWIG_0(swigCPtr, this, now, maturity, Array.getCPtr(factors), factors);
  }

  public double discountBond(double now, double maturity, double rate) {
    return QuantLibJNI.OneFactorAffineModel_discountBond__SWIG_1(swigCPtr, this, now, maturity, rate);
  }

  public double discount(double t) {
    return QuantLibJNI.OneFactorAffineModel_discount(swigCPtr, this, t);
  }

}
