/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class OptionletVolatilityStructure extends VolatilityTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected OptionletVolatilityStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.OptionletVolatilityStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionletVolatilityStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_OptionletVolatilityStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double volatility(Date arg0, double strike, boolean extrapolate) {
    return QuantLibJNI.OptionletVolatilityStructure_volatility__SWIG_0(swigCPtr, this, Date.getCPtr(arg0), arg0, strike, extrapolate);
  }

  public double volatility(Date arg0, double strike) {
    return QuantLibJNI.OptionletVolatilityStructure_volatility__SWIG_1(swigCPtr, this, Date.getCPtr(arg0), arg0, strike);
  }

  public double volatility(double arg0, double strike, boolean extrapolate) {
    return QuantLibJNI.OptionletVolatilityStructure_volatility__SWIG_2(swigCPtr, this, arg0, strike, extrapolate);
  }

  public double volatility(double arg0, double strike) {
    return QuantLibJNI.OptionletVolatilityStructure_volatility__SWIG_3(swigCPtr, this, arg0, strike);
  }

  public double blackVariance(Date arg0, double strike, boolean extrapolate) {
    return QuantLibJNI.OptionletVolatilityStructure_blackVariance__SWIG_0(swigCPtr, this, Date.getCPtr(arg0), arg0, strike, extrapolate);
  }

  public double blackVariance(Date arg0, double strike) {
    return QuantLibJNI.OptionletVolatilityStructure_blackVariance__SWIG_1(swigCPtr, this, Date.getCPtr(arg0), arg0, strike);
  }

  public double blackVariance(double arg0, double strike, boolean extrapolate) {
    return QuantLibJNI.OptionletVolatilityStructure_blackVariance__SWIG_2(swigCPtr, this, arg0, strike, extrapolate);
  }

  public double blackVariance(double arg0, double strike) {
    return QuantLibJNI.OptionletVolatilityStructure_blackVariance__SWIG_3(swigCPtr, this, arg0, strike);
  }

}
