/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class OvernightIndexFuture extends Instrument {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected OvernightIndexFuture(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.OvernightIndexFuture_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OvernightIndexFuture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_OvernightIndexFuture(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OvernightIndexFuture(OvernightIndex overnightIndex, Date valueDate, Date maturityDate, QuoteHandle convexityAdjustment, RateAveraging.Type averagingMethod) {
    this(QuantLibJNI.new_OvernightIndexFuture__SWIG_0(OvernightIndex.getCPtr(overnightIndex), overnightIndex, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment, averagingMethod.swigValue()), true);
  }

  public OvernightIndexFuture(OvernightIndex overnightIndex, Date valueDate, Date maturityDate, QuoteHandle convexityAdjustment) {
    this(QuantLibJNI.new_OvernightIndexFuture__SWIG_1(OvernightIndex.getCPtr(overnightIndex), overnightIndex, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate, QuoteHandle.getCPtr(convexityAdjustment), convexityAdjustment), true);
  }

  public OvernightIndexFuture(OvernightIndex overnightIndex, Date valueDate, Date maturityDate) {
    this(QuantLibJNI.new_OvernightIndexFuture__SWIG_2(OvernightIndex.getCPtr(overnightIndex), overnightIndex, Date.getCPtr(valueDate), valueDate, Date.getCPtr(maturityDate), maturityDate), true);
  }

  public double convexityAdjustment() {
    return QuantLibJNI.OvernightIndexFuture_convexityAdjustment(swigCPtr, this);
  }

}
