/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class QuoteVectorVector extends java.util.AbstractList<QuoteVector> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QuoteVectorVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuoteVectorVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_QuoteVectorVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QuoteVectorVector(QuoteVector[] initialElements) {
    this();
    reserve(initialElements.length);

    for (QuoteVector element : initialElements) {
      add(element);
    }
  }

  public QuoteVectorVector(Iterable<QuoteVector> initialElements) {
    this();
    for (QuoteVector element : initialElements) {
      add(element);
    }
  }

  public QuoteVector get(int index) {
    return doGet(index);
  }

  public QuoteVector set(int index, QuoteVector e) {
    return doSet(index, e);
  }

  public boolean add(QuoteVector e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, QuoteVector e) {
    modCount++;
    doAdd(index, e);
  }

  public QuoteVector remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public QuoteVectorVector() {
    this(QuantLibJNI.new_QuoteVectorVector__SWIG_0(), true);
  }

  public QuoteVectorVector(QuoteVectorVector other) {
    this(QuantLibJNI.new_QuoteVectorVector__SWIG_1(QuoteVectorVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return QuantLibJNI.QuoteVectorVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.QuoteVectorVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.QuoteVectorVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.QuoteVectorVector_clear(swigCPtr, this);
  }

  public QuoteVectorVector(int count, QuoteVector value) {
    this(QuantLibJNI.new_QuoteVectorVector__SWIG_2(count, QuoteVector.getCPtr(value), value), true);
  }

  private int doSize() {
    return QuantLibJNI.QuoteVectorVector_doSize(swigCPtr, this);
  }

  private void doAdd(QuoteVector x) {
    QuantLibJNI.QuoteVectorVector_doAdd__SWIG_0(swigCPtr, this, QuoteVector.getCPtr(x), x);
  }

  private void doAdd(int index, QuoteVector x) {
    QuantLibJNI.QuoteVectorVector_doAdd__SWIG_1(swigCPtr, this, index, QuoteVector.getCPtr(x), x);
  }

  private QuoteVector doRemove(int index) {
    return new QuoteVector(QuantLibJNI.QuoteVectorVector_doRemove(swigCPtr, this, index), true);
  }

  private QuoteVector doGet(int index) {
    return new QuoteVector(QuantLibJNI.QuoteVectorVector_doGet(swigCPtr, this, index), false);
  }

  private QuoteVector doSet(int index, QuoteVector val) {
    return new QuoteVector(QuantLibJNI.QuoteVectorVector_doSet(swigCPtr, this, index, QuoteVector.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    QuantLibJNI.QuoteVectorVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
