/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class RateHelper extends Observable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected RateHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RateHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RateHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_RateHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public QuoteHandle quote() {
    return new QuoteHandle(QuantLibJNI.RateHelper_quote(swigCPtr, this), false);
  }

  public Date latestDate() {
    return new Date(QuantLibJNI.RateHelper_latestDate(swigCPtr, this), true);
  }

  public Date earliestDate() {
    return new Date(QuantLibJNI.RateHelper_earliestDate(swigCPtr, this), true);
  }

  public Date maturityDate() {
    return new Date(QuantLibJNI.RateHelper_maturityDate(swigCPtr, this), true);
  }

  public Date latestRelevantDate() {
    return new Date(QuantLibJNI.RateHelper_latestRelevantDate(swigCPtr, this), true);
  }

  public Date pillarDate() {
    return new Date(QuantLibJNI.RateHelper_pillarDate(swigCPtr, this), true);
  }

  public double impliedQuote() {
    return QuantLibJNI.RateHelper_impliedQuote(swigCPtr, this);
  }

  public double quoteError() {
    return QuantLibJNI.RateHelper_quoteError(swigCPtr, this);
  }

}
