/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class RichardsonExtrapolation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RichardsonExtrapolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RichardsonExtrapolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RichardsonExtrapolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double getValue(double t) {
    return QuantLibJNI.RichardsonExtrapolation_getValue__SWIG_0(swigCPtr, this, t);
  }

  public double getValue() {
    return QuantLibJNI.RichardsonExtrapolation_getValue__SWIG_1(swigCPtr, this);
  }

  public double getValue(double t, double s) {
    return QuantLibJNI.RichardsonExtrapolation_getValue__SWIG_2(swigCPtr, this, t, s);
  }

  public RichardsonExtrapolation(UnaryFunctionDelegate fct, double delta_h, double n) {
    this(QuantLibJNI.new_RichardsonExtrapolation__SWIG_0(UnaryFunctionDelegate.getCPtr(fct), fct, delta_h, n), true);
  }

  public RichardsonExtrapolation(UnaryFunctionDelegate fct, double delta_h) {
    this(QuantLibJNI.new_RichardsonExtrapolation__SWIG_1(UnaryFunctionDelegate.getCPtr(fct), fct, delta_h), true);
  }

}
