/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class SampleMultiPath {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SampleMultiPath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleMultiPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_SampleMultiPath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MultiPath value() {
    return new MultiPath(QuantLibJNI.SampleMultiPath_value(swigCPtr, this), false);
  }

  public double weight() {
    return QuantLibJNI.SampleMultiPath_weight(swigCPtr, this);
  }

}
