/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class SquareRootProcessRNDCalculator extends RiskNeutralDensityCalculator {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SquareRootProcessRNDCalculator(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SquareRootProcessRNDCalculator_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SquareRootProcessRNDCalculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SquareRootProcessRNDCalculator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SquareRootProcessRNDCalculator(double v0, double kappa, double theta, double sigma) {
    this(QuantLibJNI.new_SquareRootProcessRNDCalculator(v0, kappa, theta, sigma), true);
  }

  public double stationary_pdf(double v) {
    return QuantLibJNI.SquareRootProcessRNDCalculator_stationary_pdf(swigCPtr, this, v);
  }

  public double stationary_cdf(double v) {
    return QuantLibJNI.SquareRootProcessRNDCalculator_stationary_cdf(swigCPtr, this, v);
  }

  public double stationary_invcdf(double q) {
    return QuantLibJNI.SquareRootProcessRNDCalculator_stationary_invcdf(swigCPtr, this, q);
  }

}
