/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class TermStructure extends Observable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected TermStructure(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.TermStructure_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_TermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DayCounter dayCounter() {
    return new DayCounter(QuantLibJNI.TermStructure_dayCounter(swigCPtr, this), true);
  }

  public double timeFromReference(Date date) {
    return QuantLibJNI.TermStructure_timeFromReference(swigCPtr, this, Date.getCPtr(date), date);
  }

  public Calendar calendar() {
    return new Calendar(QuantLibJNI.TermStructure_calendar(swigCPtr, this), true);
  }

  public Date referenceDate() {
    return new Date(QuantLibJNI.TermStructure_referenceDate(swigCPtr, this), true);
  }

  public Date maxDate() {
    return new Date(QuantLibJNI.TermStructure_maxDate(swigCPtr, this), true);
  }

  public double maxTime() {
    return QuantLibJNI.TermStructure_maxTime(swigCPtr, this);
  }

  public void enableExtrapolation() {
    QuantLibJNI.TermStructure_enableExtrapolation(swigCPtr, this);
  }

  public void disableExtrapolation() {
    QuantLibJNI.TermStructure_disableExtrapolation(swigCPtr, this);
  }

  public boolean allowsExtrapolation() {
    return QuantLibJNI.TermStructure_allowsExtrapolation(swigCPtr, this);
  }

}
