/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class Thirty365 extends DayCounter {
  private transient long swigCPtr;

  protected Thirty365(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.Thirty365_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Thirty365 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Thirty365(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Thirty365() {
    this(QuantLibJNI.new_Thirty365(), true);
  }

}
