/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class TreeCapFloorEngine extends PricingEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected TreeCapFloorEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.TreeCapFloorEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TreeCapFloorEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_TreeCapFloorEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TreeCapFloorEngine(ShortRateModel model, long timeSteps, YieldTermStructureHandle termStructure) {
    this(QuantLibJNI.new_TreeCapFloorEngine__SWIG_0(ShortRateModel.getCPtr(model), model, timeSteps, YieldTermStructureHandle.getCPtr(termStructure), termStructure), true);
  }

  public TreeCapFloorEngine(ShortRateModel model, long timeSteps) {
    this(QuantLibJNI.new_TreeCapFloorEngine__SWIG_1(ShortRateModel.getCPtr(model), model, timeSteps), true);
  }

  public TreeCapFloorEngine(ShortRateModel model, TimeGrid grid, YieldTermStructureHandle termStructure) {
    this(QuantLibJNI.new_TreeCapFloorEngine__SWIG_2(ShortRateModel.getCPtr(model), model, TimeGrid.getCPtr(grid), grid, YieldTermStructureHandle.getCPtr(termStructure), termStructure), true);
  }

  public TreeCapFloorEngine(ShortRateModel model, TimeGrid grid) {
    this(QuantLibJNI.new_TreeCapFloorEngine__SWIG_3(ShortRateModel.getCPtr(model), model, TimeGrid.getCPtr(grid), grid), true);
  }

}
