/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class YearOnYearInflationSwapHelper extends YoYHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YearOnYearInflationSwapHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YearOnYearInflationSwapHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YearOnYearInflationSwapHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YearOnYearInflationSwapHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YearOnYearInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bdc, DayCounter dayCounter, YoYInflationIndex index, YieldTermStructureHandle nominalTS) {
    this(QuantLibJNI.new_YearOnYearInflationSwapHelper(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bdc.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, YoYInflationIndex.getCPtr(index), index, YieldTermStructureHandle.getCPtr(nominalTS), nominalTS), true);
  }

}
