/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class YoYOptionletVolatilitySurface extends VolatilityTermStructure {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YoYOptionletVolatilitySurface(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YoYOptionletVolatilitySurface_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YoYOptionletVolatilitySurface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YoYOptionletVolatilitySurface(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Period observationLag() {
    return new Period(QuantLibJNI.YoYOptionletVolatilitySurface_observationLag(swigCPtr, this), true);
  }

  public double frequency() {
    return QuantLibJNI.YoYOptionletVolatilitySurface_frequency(swigCPtr, this);
  }

  public boolean indexIsInterpolated() {
    return QuantLibJNI.YoYOptionletVolatilitySurface_indexIsInterpolated(swigCPtr, this);
  }

  public Date baseDate() {
    return new Date(QuantLibJNI.YoYOptionletVolatilitySurface_baseDate(swigCPtr, this), true);
  }

  public double timeFromBase(Date date, Period obsLag) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_timeFromBase__SWIG_0(swigCPtr, this, Date.getCPtr(date), date, Period.getCPtr(obsLag), obsLag);
  }

  public double timeFromBase(Date date) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_timeFromBase__SWIG_1(swigCPtr, this, Date.getCPtr(date), date);
  }

  public double minStrike() {
    return QuantLibJNI.YoYOptionletVolatilitySurface_minStrike(swigCPtr, this);
  }

  public double maxStrike() {
    return QuantLibJNI.YoYOptionletVolatilitySurface_maxStrike(swigCPtr, this);
  }

  public double baseLevel() {
    return QuantLibJNI.YoYOptionletVolatilitySurface_baseLevel(swigCPtr, this);
  }

  public double volatility(Date maturityDate, double strike, Period obsLag, boolean extrapolate) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_0(swigCPtr, this, Date.getCPtr(maturityDate), maturityDate, strike, Period.getCPtr(obsLag), obsLag, extrapolate);
  }

  public double volatility(Date maturityDate, double strike, Period obsLag) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_1(swigCPtr, this, Date.getCPtr(maturityDate), maturityDate, strike, Period.getCPtr(obsLag), obsLag);
  }

  public double volatility(Date maturityDate, double strike) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_2(swigCPtr, this, Date.getCPtr(maturityDate), maturityDate, strike);
  }

  public double volatility(Period optionTenor, double strike, Period obsLag, boolean extrapolate) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_3(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike, Period.getCPtr(obsLag), obsLag, extrapolate);
  }

  public double volatility(Period optionTenor, double strike, Period obsLag) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_4(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike, Period.getCPtr(obsLag), obsLag);
  }

  public double volatility(Period optionTenor, double strike) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_volatility__SWIG_5(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike);
  }

  public double totalVariance(Date exerciseDate, double strike, Period obsLag, boolean extrapolate) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_0(swigCPtr, this, Date.getCPtr(exerciseDate), exerciseDate, strike, Period.getCPtr(obsLag), obsLag, extrapolate);
  }

  public double totalVariance(Date exerciseDate, double strike, Period obsLag) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_1(swigCPtr, this, Date.getCPtr(exerciseDate), exerciseDate, strike, Period.getCPtr(obsLag), obsLag);
  }

  public double totalVariance(Date exerciseDate, double strike) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_2(swigCPtr, this, Date.getCPtr(exerciseDate), exerciseDate, strike);
  }

  public double totalVariance(Period optionTenor, double strike, Period obsLag, boolean extrapolate) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_3(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike, Period.getCPtr(obsLag), obsLag, extrapolate);
  }

  public double totalVariance(Period optionTenor, double strike, Period obsLag) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_4(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike, Period.getCPtr(obsLag), obsLag);
  }

  public double totalVariance(Period optionTenor, double strike) {
    return QuantLibJNI.YoYOptionletVolatilitySurface_totalVariance__SWIG_5(swigCPtr, this, Period.getCPtr(optionTenor), optionTenor, strike);
  }

}
