/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class ZeroCouponInflationSwapHelper extends ZeroHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ZeroCouponInflationSwapHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ZeroCouponInflationSwapHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZeroCouponInflationSwapHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ZeroCouponInflationSwapHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bcd, DayCounter dayCounter, ZeroInflationIndex index, CPI.InterpolationType observationInterpolation, YieldTermStructureHandle nominalTS) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_0(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bcd.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, observationInterpolation.swigValue(), YieldTermStructureHandle.getCPtr(nominalTS), nominalTS), true);
  }

  public ZeroCouponInflationSwapHelper(QuoteHandle quote, Period lag, Date maturity, Calendar calendar, BusinessDayConvention bcd, DayCounter dayCounter, ZeroInflationIndex index, YieldTermStructureHandle nominalTS) {
    this(QuantLibJNI.new_ZeroCouponInflationSwapHelper__SWIG_1(QuoteHandle.getCPtr(quote), quote, Period.getCPtr(lag), lag, Date.getCPtr(maturity), maturity, Calendar.getCPtr(calendar), calendar, bcd.swigValue(), DayCounter.getCPtr(dayCounter), dayCounter, ZeroInflationIndex.getCPtr(index), index, YieldTermStructureHandle.getCPtr(nominalTS), nominalTS), true);
  }

}
